### ISSUE TITLE
Kdeconnect not working

### ISSUE THREAD

**Issue by mirek967** [celzero/docs#22]
Traffic from kdeconnect is marked as traffic from unknown application, and thus it get blocked.
This is an unexpected behavior.

**Comment by ignoramous** [comment]
Hi: Thanks for the bug report.

KDE Connect probably does a bunch of things none of which works with Rethink. We need to make changes to our code, but those aren't straight forward to do so (if they were, we'd have done them already). https://github.com/celzero/rethink-app/issues/1507

(closing this issue because it doesn't have anything to do with "docs").

**Comment by mirek967** [comment]
I see the info from the other error report. Thanks. 

Maybe it could be added an option to release application traffic on local network, and for zeroconf traffic. It could be helpful for some other applications working on local network too.

**Comment by ignoramous** [comment]
> Maybe it could be added an option to release application traffic on local network,

- You can do that by turning ON *Configure* -> *Network* -> *Do not route Private IPs*.
- You can also "Exclude" the *KDE Connect* app alone from Rethink's tunnel from *Configure* -> *Apps*.

**Comment by mirek967** [comment]
Thank you. 
I did that. Now it works.
